/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const ElInput: typeof import('element-plus/es').ElInput
  const ElSelect: typeof import('element-plus/es').ElSelect
}
